### ISSUE TITLE
Convert TAXID lineage to character-based lineage

### ISSUE THREAD

**Issue by ktmbiome** [pirovc/ganon#296]
Hello again!

I am interested in converting the TAXID-based lineages to the name-based lineages. However, I have also used both the refseq and gtdb databases. Realizing that they are essentially subsets of each other, is there a way to translate the taxonomies in the combined file to something unified and ideally outside of the taxid format (though I could possibly use another software to translate harmonized taxids)?

Is there a good way to do it that you see using ganon, or is it better to do this with custom scripts?

Thank you!

**Comment by ktmbiome-niaid** [comment]
I've been thinking about this a bit more, and I think it could work if I could get the genome names as the taxID for GTDB assignments (GCA_018383205.1) instead of the species name (Lawsonibacter sp900754605). I could then create a taxid table, splitting out RefSeq from GTDB, using taxonkit (or something similar) on both independently and then pasting them back together. Does that seem like a possible approach?

**Comment by pirovc** [comment]
I didn't completely understand what you're trying to achieve. Could you give some examples? Here some thoughts.

- The GTDB references are indeed based on a sub-set of RefSeq, but it uses a different taxonomy that is not 1-to-1 to the NCBI.
- ganon uses [MultiTax](https://github.com/pirovc/multitax) under the hood to handle taxonomies, you could try to see if it fits your needs. It offers taxid and name translations and even conversion from GTDB to NCBI, but this is limited.
- ganon can also perform classification at assembly, sequence or file level (you have to build the database accordingly) and that may be what you are looking for.

**Comment by ktmbiome-niaid** [comment]
Thank you! I was able to do pretty much exactly what I needed to do with your MultiTax package, and I'm not even a fully-proficient python programmer! I really appreciate all of your help!
