### ISSUE TITLE
Invalid sequences in build step

### ISSUE THREAD

**Issue by mdehollander** [pirovc/ganon#53]
While building a reference db for fungal sequences from genbank, all of them are marked as invalid during the build process. What makes them invalid?

```
FJUY01000046.1 not defined on seqid-bin file

ganon-build processed 0 sequences (0 Mbp) in 154.275 seconds (0 Kseq/m, 0 Mbp/m)
 - 73767 sequences and 1446 bins defined on ganon-genbank-fungi_tmp/acc_bin.txt
 - 87436 sequences (87436 invalid) were read from the input sequence files.
 - 0 valid sequences in 1446 bins were written to ganon-genbank-fungi.filter
Done. Elapsed time: 177.28528761863708 seconds.
Storing nodes... Done. Elapsed time: 3.003349542617798 seconds.
Total elapsed time: 206.2393398284912 seconds.
```

In the `2019-02-20_15-51-10_updated_sequence_accession.txt` from `genome_updater` the stats look ok.

```
A       GCA_900074925.1 FJUY01000031.1  NW_019716285.1  109818  112498
```

The fasta header look like:
```
>FJUY01000077.1 Ramularia collo-cygni strain URUG2 genome assembly, contig: RCC_scaffold77, whole genome shotgun sequence
```

**Comment by pirovc** [comment]
Hi @mdehollander 

ganon input for building an index is a tab separated file with the fields:
`accession <tab> seq. length <tab> taxid [ <tab> assembly accession]`

the assembly accession column is only required for assembly level databases.

The input is automatically generated from the NCBI web services (that can take a while) or can be provided by the user with the `--len-taxid-file` parameter. Since you have the `*_updated_sequence_accession.txt` from [genome_updater](https://github.com/pirovc/genome_updater) you can direcly extract the information with the following (as said in #50):

RefSeq:
`awk 'BEGIN {FS="\t";OFS="\t"}{if($4!="na"){ print $4,$5,$6,$2 }}' download_folder/TIMESTAMP_updated_sequence_accession.txt > acc_len_taxid_assembly.txt`

Genbank:
`awk 'BEGIN {FS="\t";OFS="\t"}{if($4!="na"){ print $3,$5,$6,$2 }}' download_folder/TIMESTAMP_updated_sequence_accession.txt > acc_len_taxid_assembly.txt`

I guess your `acc_len_taxid_assembly.txt` is probably with the refseq accessions.

The `acc_len_taxid_assembly.txt` should look like:

Refseq:
`GCA_900074925.1	109818	112498	GCA_900074925.1`

Genbank:
`FJUY01000031.1	109818	112498	GCA_900074925.1`

**Comment by mdehollander** [comment]
Thanks! I think that for Genbank the column to check for na's is the 3rd. At least this command 
```
awk 'BEGIN {FS="\t";OFS="\t"}{if($3!="na"){ print $3,$5,$6,$2 }}' 2019-02-20_15-51-10_updated_sequence_accession.txt > acc_len_taxid_assembly.txt
```
produces output like this:
```
FJUY01000031.1  109818  112498  GCA_900074925.1
```

And then the building step finishes, although a few sequences are still invalid. I am not sure why they are invalid
```
AWWW01005683.1 not defined on seqid-bin file
AWWW01005684.1 not defined on seqid-bin file
AWWW01005685.1 not defined on seqid-bin file
AWWW01005686.1 not defined on seqid-bin file

ganon-build processed 6181048 sequences (64776.6 Mbp) in 4206.32 seconds (88.168 Kseq/m, 923.99 Mbp/m)
 - 6181048 sequences and 11782 bins defined on ganon-genbank-fungi_tmp/acc_bin.txt
 - 6194974 sequences (13926 invalid) were read from the input sequence files.
 - 6181048 valid sequences in 11782 bins were written to ganon-genbank-fungi.filter
Done. Elapsed time: 4367.664316654205 seconds.
Storing nodes... Done. Elapsed time: 3.22529935836792 seconds.
Total elapsed time: 4787.669978380203 seconds.
```

**Comment by pirovc** [comment]
The sequences are invalid when they are not present on the `--len-taxid-file` or if they are smaller than the k size choosen.

Sometime a sequence is present in the `--len-taxid-file` but it's taxonomic id was not found in the version nodes.dmp (and merged.dmp) provided, so TaxSBP will not cluster then (and it will output a warning: `[SEQID] skipped - taxid not found in nodes/merged file`.

All ignored sequences should be listed in the STDERR with information why they were invalidated.

**Comment by mdehollander** [comment]
Ok, thanks for the explanation
