### ISSUE TITLE
Comparison of run-time classification step

### ISSUE THREAD

**Issue by mdehollander** [pirovc/ganon#57]
I ran `ganon classify` and kraken1 on the same samples against a db build of NCBI fungal genbank sequences. I noticed that ganon took much longer than kraken1 to process the sequences:

```
analysis/ganon/T7V21.log:ganon-classify processed 1017638 sequences (270.743 Mbp) in 1348.76 seconds (45.2699 Kseq/m, 12.0441 Mbp/m)
analysis/kraken/T7V21.log:1017638 sequences (270.74 Mbp) processed in 38.897s (1569.7 Kseq/m, 417.63 Mbp/m).
```

The databases are located on PCI Express (PCIe) storage. The ganon filter file is 54 GB where the kraken1 kdb file is 546 GB (!), so the ganon db is also much smaller.

I was expecting ganon to be faster or even comparable.   Is this expected? Should I change something? Any thoughts on this are appreciated.

**Comment by pirovc** [comment]
How many threads are you using? ganon scales very well with more threads and you should have a noticible speed-up.

There are some optimizations that can be done to speed-up ganon, from the way you build the filter (`--fragment-length 0` on build) to the usage with offsets (`--offset 2` on classify - have to recompile the binaires with `-DGANON_OFFSET=ON`). In the next weeks I'll update the pre-print with some more details about those variables.

But you are right, kraken is indeed faster. That's because the way it was design and its data structure. Ganon does not aim to improve on classification performance but offers other features, so it's trade-off.

**Comment by mdehollander** [comment]
Yeah, threads, forgot to mention that. I used 8 for both. I will try with 24 so see its performance.

I am already happy that updating databases in the future should be more easy. And the time to build a database for ganon is also much shorter compared to kraken. So indeed, speed is not everything.

**Comment by mdehollander** [comment]
I ran kraken and ganon both with 48 threads:

```
analysis/ganon/T7V21.log:ganon-classify processed 1017638 sequences (270.743 Mbp) in 169.41 seconds (360.416 Kseq/m, 95.8889 Mbp/m)
analysis/kraken/T7V21.log:1017638 sequences (270.74 Mbp) processed in 9.093s (6714.6 Kseq/m, 1786.42 Mbp/m).
```

Ganon is indeed gaining more in performance compared to kraken when they get more threads.
